# Generated by Django 3.0.7 on 2020-06-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answered_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
